package(default_visibility = ["//visibility:public"])

java_library(
    name = "metrics",
    srcs = glob(["**/*.java"]),
    deps = [
        "@io_netty_netty_all//jar",
        "@io_prometheus_simpleclient//jar",
        "@io_prometheus_simpleclient_common//jar",
        "@org_slf4j_slf4j_api//jar",
    ],
)
