apiVersion: "coreos.com/v1"
kind: "EtcdCluster"
metadata:
  name: "etcd-global"
spec:
  size: 3
  version: "v3.1.0-alpha.1"
  backup:
    snapshotIntervalInSecond: 3600
    maxBackups: 5
    volumeSizeInMB: 512
    storageType: "PersistentVolume"
  template:
    metadata:
      labels:
        component: etcd
        cell: global
        app: vitess
