# This is the service that external clients will use to send rpcs to the greeter service.
apiVersion: v1
kind: Service
metadata:
  name: greeter
  labels:
    app: greeter
spec:
  type: LoadBalancer
  ports:
  - name: rpc
    protocol: TCP
    port: 50051
    targetPort: rpc
  selector:
    app: greeter
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: greeter-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: greeter
    spec:
      containers:
      - name: greeter
        image: asia.gcr.io/sh-compute-projects/greeter_container:v0.1.3
        ports:
        - name: web
          containerPort: 9090
          protocol: TCP
        - name: rpc
          containerPort: 50051
          protocol: TCP
        # Specify vtgate instance to connect to.
        args:
          - vtgate-asiaeast1c:15991
